authors:
  none:
    name: none
    description: title
    avatar: http://link
    
  marcel:
    name: Marcel
    description: Creator
    avatar: https://pbs.twimg.com/profile_images/1814414039574810624/kooT_8_v_400x400.jpg
