# .github/workflows/deploy.yml
name: Deploy Docs
on:
  push:
    branches: [main]

# PERMISSÕES ADICIONADAS AQUI ↓
permissions:
  contents: write  # Permite escrever no branch gh-pages

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Necessário para o mkdocs gh-deploy

      - uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - run: pip install mkdocs mkdocs-material

      # Configura o Git corretamente ↓
      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - run: mkdocs gh-deploy --force
        env:
          # Usa o token de acesso especial
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Já incluso automaticamente
